cmd: "mocha"
errorMatch:
  - ([\d+]\) )(?<message>.+:(?:\r|\n|.)*?)at.*\((?<file>[\/0-9a-zA-Z\._]+):(?<line>\d+):(?<col>\d+)\)
  - not ok \d (?<message>.+\n.+)\n\s+at(.|\n)+\((?<file>[\/0-9a-zA-Z\._]+):(?<line>\d+):(?<col>\d+)\)
  # - \((?<file>[\/0-9a-zA-Z\._]+):(?<line>\d+):(?<col>\d+)\)
